version: "3"

services:
    webserver:
        build: ./bin/webserver
        ports:
            - "8084:80"
        volumes:
            - ./www/html:/var/www/html/
            - ./config/php:/usr/local/etc/php
            - ./config/apache2_config/apache2.conf:/etc/apache2/apache2.conf
            - ./logs/php:/var/log/apache2
            - ./etc/hosts:/etc/hosts
        links:
          - mysql
        networks:
            - default
    mysql:
        image: mysql:8.0.26
        container_name: 'sever-mysql'
        restart: 'always'
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        depends_on:
          - mysql
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
          - 8010:80
        environment:
          PMA_HOST: mysql
          UPLOAD_LIMIT: 200M
volumes:
    persistent:
